/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AuthorizedGroup;
import io.swagger.client.model.AuthorizedUser;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AuthorizedSubjects
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class AuthorizedSubjects {
  @SerializedName("users")
  private List<AuthorizedUser> users = null;

  @SerializedName("groups")
  private List<AuthorizedGroup> groups = null;

  public AuthorizedSubjects users(List<AuthorizedUser> users) {
    this.users = users;
    return this;
  }

  public AuthorizedSubjects addUsersItem(AuthorizedUser usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<AuthorizedUser>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @ApiModelProperty(value = "")
  public List<AuthorizedUser> getUsers() {
    return users;
  }

  public void setUsers(List<AuthorizedUser> users) {
    this.users = users;
  }

  public AuthorizedSubjects groups(List<AuthorizedGroup> groups) {
    this.groups = groups;
    return this;
  }

  public AuthorizedSubjects addGroupsItem(AuthorizedGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<AuthorizedGroup>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<AuthorizedGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<AuthorizedGroup> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizedSubjects authorizedSubjects = (AuthorizedSubjects) o;
    return Objects.equals(this.users, authorizedSubjects.users) &&
        Objects.equals(this.groups, authorizedSubjects.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(users, groups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizedSubjects {\n");
    
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

