/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BehaviorRuleElementConfiguration;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * BehaviorRuleElementConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class BehaviorRuleElementConfiguration {
  @SerializedName("type")
  private String type = null;

  @SerializedName("values")
  private Map<String, String> values = null;

  @SerializedName("children")
  private List<BehaviorRuleElementConfiguration> children = null;

  public BehaviorRuleElementConfiguration type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BehaviorRuleElementConfiguration values(Map<String, String> values) {
    this.values = values;
    return this;
  }

  public BehaviorRuleElementConfiguration putValuesItem(String key, String valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<String, String>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getValues() {
    return values;
  }

  public void setValues(Map<String, String> values) {
    this.values = values;
  }

  public BehaviorRuleElementConfiguration children(List<BehaviorRuleElementConfiguration> children) {
    this.children = children;
    return this;
  }

  public BehaviorRuleElementConfiguration addChildrenItem(BehaviorRuleElementConfiguration childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<BehaviorRuleElementConfiguration>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<BehaviorRuleElementConfiguration> getChildren() {
    return children;
  }

  public void setChildren(List<BehaviorRuleElementConfiguration> children) {
    this.children = children;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BehaviorRuleElementConfiguration behaviorRuleElementConfiguration = (BehaviorRuleElementConfiguration) o;
    return Objects.equals(this.type, behaviorRuleElementConfiguration.type) &&
        Objects.equals(this.values, behaviorRuleElementConfiguration.values) &&
        Objects.equals(this.children, behaviorRuleElementConfiguration.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, values, children);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BehaviorRuleElementConfiguration {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

