/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChannelConnector;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BotConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class BotConfiguration {
  @SerializedName("packages")
  private List<String> packages = null;

  @SerializedName("channels")
  private List<ChannelConnector> channels = null;

  public BotConfiguration packages(List<String> packages) {
    this.packages = packages;
    return this;
  }

  public BotConfiguration addPackagesItem(String packagesItem) {
    if (this.packages == null) {
      this.packages = new ArrayList<String>();
    }
    this.packages.add(packagesItem);
    return this;
  }

   /**
   * Get packages
   * @return packages
  **/
  @ApiModelProperty(value = "")
  public List<String> getPackages() {
    return packages;
  }

  public void setPackages(List<String> packages) {
    this.packages = packages;
  }

  public BotConfiguration channels(List<ChannelConnector> channels) {
    this.channels = channels;
    return this;
  }

  public BotConfiguration addChannelsItem(ChannelConnector channelsItem) {
    if (this.channels == null) {
      this.channels = new ArrayList<ChannelConnector>();
    }
    this.channels.add(channelsItem);
    return this;
  }

   /**
   * Get channels
   * @return channels
  **/
  @ApiModelProperty(value = "")
  public List<ChannelConnector> getChannels() {
    return channels;
  }

  public void setChannels(List<ChannelConnector> channels) {
    this.channels = channels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BotConfiguration botConfiguration = (BotConfiguration) o;
    return Objects.equals(this.packages, botConfiguration.packages) &&
        Objects.equals(this.channels, botConfiguration.channels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packages, channels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BotConfiguration {\n");
    
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

