/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ConversationStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class ConversationStatus {
  @SerializedName("conversationId")
  private String conversationId = null;

  @SerializedName("botId")
  private String botId = null;

  @SerializedName("botVersion")
  private Integer botVersion = null;

  /**
   * Gets or Sets conversationState
   */
  @JsonAdapter(ConversationStateEnum.Adapter.class)
  public enum ConversationStateEnum {
    READY("READY"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    ENDED("ENDED"),
    
    EXECUTION_INTERRUPTED("EXECUTION_INTERRUPTED"),
    
    ERROR("ERROR");

    private String value;

    ConversationStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConversationStateEnum fromValue(String text) {
      for (ConversationStateEnum b : ConversationStateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ConversationStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConversationStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConversationStateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ConversationStateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("conversationState")
  private ConversationStateEnum conversationState = null;

  @SerializedName("lastInteraction")
  private OffsetDateTime lastInteraction = null;

  public ConversationStatus conversationId(String conversationId) {
    this.conversationId = conversationId;
    return this;
  }

   /**
   * Get conversationId
   * @return conversationId
  **/
  @ApiModelProperty(value = "")
  public String getConversationId() {
    return conversationId;
  }

  public void setConversationId(String conversationId) {
    this.conversationId = conversationId;
  }

  public ConversationStatus botId(String botId) {
    this.botId = botId;
    return this;
  }

   /**
   * Get botId
   * @return botId
  **/
  @ApiModelProperty(value = "")
  public String getBotId() {
    return botId;
  }

  public void setBotId(String botId) {
    this.botId = botId;
  }

  public ConversationStatus botVersion(Integer botVersion) {
    this.botVersion = botVersion;
    return this;
  }

   /**
   * Get botVersion
   * @return botVersion
  **/
  @ApiModelProperty(value = "")
  public Integer getBotVersion() {
    return botVersion;
  }

  public void setBotVersion(Integer botVersion) {
    this.botVersion = botVersion;
  }

  public ConversationStatus conversationState(ConversationStateEnum conversationState) {
    this.conversationState = conversationState;
    return this;
  }

   /**
   * Get conversationState
   * @return conversationState
  **/
  @ApiModelProperty(value = "")
  public ConversationStateEnum getConversationState() {
    return conversationState;
  }

  public void setConversationState(ConversationStateEnum conversationState) {
    this.conversationState = conversationState;
  }

  public ConversationStatus lastInteraction(OffsetDateTime lastInteraction) {
    this.lastInteraction = lastInteraction;
    return this;
  }

   /**
   * Get lastInteraction
   * @return lastInteraction
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastInteraction() {
    return lastInteraction;
  }

  public void setLastInteraction(OffsetDateTime lastInteraction) {
    this.lastInteraction = lastInteraction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationStatus conversationStatus = (ConversationStatus) o;
    return Objects.equals(this.conversationId, conversationStatus.conversationId) &&
        Objects.equals(this.botId, conversationStatus.botId) &&
        Objects.equals(this.botVersion, conversationStatus.botVersion) &&
        Objects.equals(this.conversationState, conversationStatus.conversationState) &&
        Objects.equals(this.lastInteraction, conversationStatus.lastInteraction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conversationId, botId, botVersion, conversationState, lastInteraction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationStatus {\n");
    
    sb.append("    conversationId: ").append(toIndentedString(conversationId)).append("\n");
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    botVersion: ").append(toIndentedString(botVersion)).append("\n");
    sb.append("    conversationState: ").append(toIndentedString(conversationState)).append("\n");
    sb.append("    lastInteraction: ").append(toIndentedString(lastInteraction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

