/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.HttpCall;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HttpCallsConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class HttpCallsConfiguration {
  @SerializedName("targetServer")
  private String targetServer = null;

  @SerializedName("httpCalls")
  private List<HttpCall> httpCalls = null;

  public HttpCallsConfiguration targetServer(String targetServer) {
    this.targetServer = targetServer;
    return this;
  }

   /**
   * Get targetServer
   * @return targetServer
  **/
  @ApiModelProperty(value = "")
  public String getTargetServer() {
    return targetServer;
  }

  public void setTargetServer(String targetServer) {
    this.targetServer = targetServer;
  }

  public HttpCallsConfiguration httpCalls(List<HttpCall> httpCalls) {
    this.httpCalls = httpCalls;
    return this;
  }

  public HttpCallsConfiguration addHttpCallsItem(HttpCall httpCallsItem) {
    if (this.httpCalls == null) {
      this.httpCalls = new ArrayList<HttpCall>();
    }
    this.httpCalls.add(httpCallsItem);
    return this;
  }

   /**
   * Get httpCalls
   * @return httpCalls
  **/
  @ApiModelProperty(value = "")
  public List<HttpCall> getHttpCalls() {
    return httpCalls;
  }

  public void setHttpCalls(List<HttpCall> httpCalls) {
    this.httpCalls = httpCalls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpCallsConfiguration httpCallsConfiguration = (HttpCallsConfiguration) o;
    return Objects.equals(this.targetServer, httpCallsConfiguration.targetServer) &&
        Objects.equals(this.httpCalls, httpCallsConfiguration.httpCalls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetServer, httpCalls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpCallsConfiguration {\n");
    
    sb.append("    targetServer: ").append(toIndentedString(targetServer)).append("\n");
    sb.append("    httpCalls: ").append(toIndentedString(httpCalls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

