/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OutputType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class OutputType {
  @SerializedName("type")
  private String type = null;

  @SerializedName("valueAlternatives")
  private List<String> valueAlternatives = null;

  public OutputType type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public OutputType valueAlternatives(List<String> valueAlternatives) {
    this.valueAlternatives = valueAlternatives;
    return this;
  }

  public OutputType addValueAlternativesItem(String valueAlternativesItem) {
    if (this.valueAlternatives == null) {
      this.valueAlternatives = new ArrayList<String>();
    }
    this.valueAlternatives.add(valueAlternativesItem);
    return this;
  }

   /**
   * Get valueAlternatives
   * @return valueAlternatives
  **/
  @ApiModelProperty(value = "")
  public List<String> getValueAlternatives() {
    return valueAlternatives;
  }

  public void setValueAlternatives(List<String> valueAlternatives) {
    this.valueAlternatives = valueAlternatives;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputType outputType = (OutputType) o;
    return Objects.equals(this.type, outputType.type) &&
        Objects.equals(this.valueAlternatives, outputType.valueAlternatives);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, valueAlternatives);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputType {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    valueAlternatives: ").append(toIndentedString(valueAlternatives)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

