/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PhraseConfiguration;
import io.swagger.client.model.WordConfiguration;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RegularDictionaryConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-13T23:55:01.697Z")
public class RegularDictionaryConfiguration {
  @SerializedName("words")
  private List<WordConfiguration> words = null;

  @SerializedName("phrases")
  private List<PhraseConfiguration> phrases = null;

  public RegularDictionaryConfiguration words(List<WordConfiguration> words) {
    this.words = words;
    return this;
  }

  public RegularDictionaryConfiguration addWordsItem(WordConfiguration wordsItem) {
    if (this.words == null) {
      this.words = new ArrayList<WordConfiguration>();
    }
    this.words.add(wordsItem);
    return this;
  }

   /**
   * Get words
   * @return words
  **/
  @ApiModelProperty(value = "")
  public List<WordConfiguration> getWords() {
    return words;
  }

  public void setWords(List<WordConfiguration> words) {
    this.words = words;
  }

  public RegularDictionaryConfiguration phrases(List<PhraseConfiguration> phrases) {
    this.phrases = phrases;
    return this;
  }

  public RegularDictionaryConfiguration addPhrasesItem(PhraseConfiguration phrasesItem) {
    if (this.phrases == null) {
      this.phrases = new ArrayList<PhraseConfiguration>();
    }
    this.phrases.add(phrasesItem);
    return this;
  }

   /**
   * Get phrases
   * @return phrases
  **/
  @ApiModelProperty(value = "")
  public List<PhraseConfiguration> getPhrases() {
    return phrases;
  }

  public void setPhrases(List<PhraseConfiguration> phrases) {
    this.phrases = phrases;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegularDictionaryConfiguration regularDictionaryConfiguration = (RegularDictionaryConfiguration) o;
    return Objects.equals(this.words, regularDictionaryConfiguration.words) &&
        Objects.equals(this.phrases, regularDictionaryConfiguration.phrases);
  }

  @Override
  public int hashCode() {
    return Objects.hash(words, phrases);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegularDictionaryConfiguration {\n");
    
    sb.append("    words: ").append(toIndentedString(words)).append("\n");
    sb.append("    phrases: ").append(toIndentedString(phrases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

