/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.SimpleConversationMemorySnapshot;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BotEngineApi
 */
@Ignore
public class BotEngineApiTest {

    private final BotEngineApi api = new BotEngineApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConversationStateTest() throws ApiException {
        String environment = null;
        String conversationId = null;
        String response = api.getConversationState(environment, conversationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isRedoAvailableTest() throws ApiException {
        String environment = null;
        String botId = null;
        String conversationId = null;
        Boolean response = api.isRedoAvailable(environment, botId, conversationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isUndoAvailableTest() throws ApiException {
        String environment = null;
        String botId = null;
        String conversationId = null;
        Boolean response = api.isUndoAvailable(environment, botId, conversationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readConversationTest() throws ApiException {
        String environment = null;
        String botId = null;
        String conversationId = null;
        Boolean returnDetailed = null;
        SimpleConversationMemorySnapshot response = api.readConversation(environment, botId, conversationId, returnDetailed);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void redoTest() throws ApiException {
        String environment = null;
        String botId = null;
        String conversationId = null;
        api.redo(environment, botId, conversationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sayTest() throws ApiException {
        String environment = null;
        String botId = null;
        String conversationId = null;
        Boolean returnDetailed = null;
        Boolean returnCurrentStepOnly = null;
        String body = null;
        api.say(environment, botId, conversationId, returnDetailed, returnCurrentStepOnly, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startConversationTest() throws ApiException {
        String environment = null;
        String botId = null;
        api.startConversation(environment, botId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void undoTest() throws ApiException {
        String environment = null;
        String botId = null;
        String conversationId = null;
        api.undo(environment, botId, conversationId);

        // TODO: test validations
    }
    
}
