/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExpressionsApi
 */
@Ignore
public class ExpressionsApiTest {

    private final ExpressionsApi api = new ExpressionsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readExpressionsTest() throws ApiException {
        String packageId = null;
        Integer packageVersion = null;
        String filter = null;
        Integer limit = null;
        List<String> response = api.readExpressions(packageId, packageVersion, filter, limit);

        // TODO: test validations
    }
    
}
