/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SemanticParserApi
 */
@Ignore
public class SemanticParserApiTest {

    private final SemanticParserApi api = new SemanticParserApi();

    
    /**
     * returns an array of found solutions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void parse1Test() throws ApiException {
        String parserId = null;
        Integer version = null;
        String body = null;
        api.parse1(parserId, version, body);

        // TODO: test validations
    }
    
}
