/*
 * EDDI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PatchInstructionSimpleTestCaseDescriptor;
import io.swagger.client.model.TestCase;
import io.swagger.client.model.TestCaseDescriptor;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestcasesApi
 */
@Ignore
public class TestcasesApiTest {

    private final TestcasesApi api = new TestcasesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTestCaseTest() throws ApiException {
        String body = null;
        api.createTestCase(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTestCaseTest() throws ApiException {
        String id = null;
        api.deleteTestCase(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestCaseStateTest() throws ApiException {
        String id = null;
        String response = api.getTestCaseState(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchDescriptorTest() throws ApiException {
        String id = null;
        Integer version = null;
        PatchInstructionSimpleTestCaseDescriptor body = null;
        api.patchDescriptor(id, version, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readTestCaseTest() throws ApiException {
        String id = null;
        TestCase response = api.readTestCase(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readTestCaseDescriptorsTest() throws ApiException {
        String botId = null;
        Integer botVersion = null;
        Integer index = null;
        Integer limit = null;
        List<TestCaseDescriptor> response = api.readTestCaseDescriptors(botId, botVersion, index, limit);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runTestCaseTest() throws ApiException {
        String id = null;
        api.runTestCase(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTestCaseTest() throws ApiException {
        String id = null;
        TestCase body = null;
        String response = api.updateTestCase(id, body);

        // TODO: test validations
    }
    
}
